# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-12-03 17:54+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: .././gecosws_config_assistant/controller/AutoSetupController.py:107
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:107
msgid "The URL field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:107
#: .././gecosws_config_assistant/controller/AutoSetupController.py:122
#: .././gecosws_config_assistant/controller/AutoSetupController.py:130
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:107
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:151
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:183
#: .././gecosws_config_assistant/controller/LocalUserController.py:76
#: .././gecosws_config_assistant/controller/LocalUserController.py:92
#: .././gecosws_config_assistant/controller/LocalUserController.py:101
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:364
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:379
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:399
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:422
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:431
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:440
#: .././gecosws_config_assistant/view/LocalUserElemView.py:156
msgid "Please fill all the mandatory fields."
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:114
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
msgid "Malformed URL in URL field!"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:114
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:114
msgid "Please double-check it."
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:122
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:122
msgid "The Username field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:130
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:130
msgid "The Password field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:138
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:138
msgid "Can't connect to GECOS CC!"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:138
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:138
msgid "Please double-check all the data and your network setup."
msgstr ""

#. Show process view
#. Get auto setup JSON
#: .././gecosws_config_assistant/controller/AutoSetupController.py:160
msgid "Please wait"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:170
msgid "Error getting data"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:171
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""

#: .././gecosws_config_assistant/controller/AutoSetupController.py:176
msgid "Success getting data from GECOS server"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:151
msgid "The GECOS workstation name field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:170
msgid "The GECOS workstation name already exist!"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:170
msgid "Please choose a different name."
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:183
msgid "You must select an OU!"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:226
#: .././gecosws_config_assistant/util/Template.py:132
msgid "Can not find user to be used as owner: "
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:233
#: .././gecosws_config_assistant/util/Template.py:139
msgid "Can not find group to be used as owner: "
msgstr ""

#. Linking/unlinking to Chef server
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:298
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:85
msgid "Link to Chef"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:299
msgid "Register in GECOS CC"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:304
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:325
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:332
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:369
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:450
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:476
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:497
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:504
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:511
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:548
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:672
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:683
msgid "IN PROCESS"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:308
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:314
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:320
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:327
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:361
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:406
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:418
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:440
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:459
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:468
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:499
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:506
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:540
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:555
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:578
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:615
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:624
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:633
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:643
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:652
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:661
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:675
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:134
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:139
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:144
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:153
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:163
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:168
#: .././gecosws_config_assistant/view/GecosCCSetupProgressView.py:99
#: .././gecosws_config_assistant/view/GecosCCSetupProgressView.py:104
#: .././gecosws_config_assistant/view/GecosCCSetupProgressView.py:109
#: .././gecosws_config_assistant/view/GecosCCSetupProgressView.py:118
#: .././gecosws_config_assistant/view/GecosCCSetupProgressView.py:127
#: .././gecosws_config_assistant/view/GecosCCSetupProgressView.py:132
msgid "ERROR"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:324
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:331
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:368
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:449
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:475
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:481
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:503
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:510
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:547
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:671
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:682
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:689
msgid "DONE"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:353
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:532
msgid "CANCELED"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:363
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:542
msgid "There was an error while saving validation certificate"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:408
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:580
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:420
msgid "Can't link to chef server"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:442
msgid "Can't create/modify /etc/chef.control file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:461
msgid "Can't register the computer in GECOS CC"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:470
msgid "Can't save /etc/gcc.control file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:491
msgid "Unlink from Chef"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:492
msgid "Unregister from GECOS CC"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:557
msgid "Can't unregister the computer from GECOS CC"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:617
msgid "Can't create/modify /etc/chef/knife.rb file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:626
msgid "Can't remove /etc/chef.control file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:635
msgid "Can't remove /etc/chef/client.pem file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:645
#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:662
msgid "Can't delete Chef node"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:654
msgid "Can't remove /usr/bin/chef-client-wrapper file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:677
msgid "Can't remove /etc/gcc.control file"
msgstr ""

#: .././gecosws_config_assistant/controller/ConnectWithGecosCCController.py:707
msgid "Can't get OUs from GECOS Control Center"
msgstr ""

#: .././gecosws_config_assistant/controller/LocalUserController.py:76
msgid "The login field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/LocalUserController.py:83
msgid "The login field contains not allowed characters!"
msgstr ""

#: .././gecosws_config_assistant/controller/LocalUserController.py:92
msgid "The name field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/LocalUserController.py:101
msgid "The password field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/LocalUserController.py:109
msgid "The password field contains not allowed characters."
msgstr ""

#: .././gecosws_config_assistant/controller/LocalUserController.py:157
msgid "Do you really want to delete this user? "
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:179
msgid "The system has a network connection configured"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:181
msgid "The system has NO network connection"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:184
msgid "The system has loaded setup data values from GECOS server"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:186
msgid "The system may load setup data values from GECOS server"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:189
msgid "The system is synchronized with a NTP server"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:191
msgid "The system is NOT synchronized with a NTP server"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:194
msgid "The system is linked to a GECOS server"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:196
msgid "The system is NOT linked to a GECOS server"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:198
#, python-format
msgid "Users authenticate by %s method"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:203
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:227
#: .././gecosws_config_assistant/dto/LDAPAuthMethod.py:43
#: .././gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
#: .././gecosws_config_assistant/view/UserAuthDialog.py:64
#: .././gecosws_config_assistant/view/UserAuthDialog.py:145
#: .././gecosws_config_assistant/view/UserAuthDialog.py:187
#: .././gecosws_config_assistant/view/UserAuthDialog.py:381
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:296
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:314
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:334
msgid "LDAP"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:205
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:229
#: .././gecosws_config_assistant/dto/ADAuthMethod.py:44
#: .././gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
#: .././gecosws_config_assistant/view/UserAuthDialog.py:64
#: .././gecosws_config_assistant/view/UserAuthDialog.py:147
#: .././gecosws_config_assistant/view/UserAuthDialog.py:189
#: .././gecosws_config_assistant/view/UserAuthDialog.py:393
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:298
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:311
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:345
msgid "Active Directory"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:207
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:225
#: .././gecosws_config_assistant/dto/LocalUsersAuthMethod.py:43
#: .././gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
#: .././gecosws_config_assistant/view/UserAuthDialog.py:64
#: .././gecosws_config_assistant/view/UserAuthDialog.py:143
#: .././gecosws_config_assistant/view/UserAuthDialog.py:185
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:99
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:101
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:317
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:323
msgid "Internal"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:270
msgid "Are you sure you want to update the GECOS Config Assistant?"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:273
#: .././gecosws_config_assistant/controller/MainMenuController.py:281
msgid "An error occurred during the upgrade"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:277
msgid "CGA is already at the newest version!"
msgstr ""

#: .././gecosws_config_assistant/controller/MainMenuController.py:279
msgid "GECOS Config Assistant has been udpated. Please restart GCA"
msgstr ""

#. Show error message
#: .././gecosws_config_assistant/controller/NTPServerController.py:70
#: .././gecosws_config_assistant/controller/NTPServerController.py:74
msgid "Error saving NTP server data."
msgstr ""

#: .././gecosws_config_assistant/controller/NTPServerController.py:70
#: .././gecosws_config_assistant/controller/NTPServerController.py:74
#: .././gecosws_config_assistant/view/UserAuthDialog.py:364
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "See log for more details."
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:299
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:364
msgid "The URI field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:371
msgid "Malformed LDAP URI!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:371
msgid "Please check that the URI starts with 'ldap://' or 'ldaps://'."
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:379
msgid "The users base DN field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:386
msgid "Can't connect to LDAP server!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:386
#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:448
msgid "Please check all the fields and your network connection."
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:399
msgid "The Domain field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:413
msgid "Can't resolv the Active Directory Domain name!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:414
msgid "Please check the Domain field and your DNS configuration."
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:422
msgid "The Workgroup field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:430
msgid "The AD administrator user field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:439
msgid "The AD administrator password field is empty!"
msgstr ""

#: .././gecosws_config_assistant/controller/UserAuthenticationMethodController.py:447
msgid "Can't connect to Active Directory server!"
msgstr ""

#: .././gecosws_config_assistant/dao/GecosAccessDataDAO.py:178
#: .././gecosws_config_assistant/dao/WorkstationDataDAO.py:183
msgid "Error removing file:"
msgstr ""

#: .././gecosws_config_assistant/dao/LocalUserDAO.py:119
msgid "Error creating user: "
msgstr ""

#: .././gecosws_config_assistant/dao/LocalUserDAO.py:131
msgid "Error modifying user name: "
msgstr ""

#: .././gecosws_config_assistant/dao/LocalUserDAO.py:145
msgid "Error modifying user password: "
msgstr ""

#: .././gecosws_config_assistant/dao/LocalUserDAO.py:169
msgid "Error deleting user: "
msgstr ""

#: .././gecosws_config_assistant/dao/LocalUserDAO.py:179
msgid "Error deleting user home: "
msgstr ""

#: .././gecosws_config_assistant/dao/NTPServerDAO.py:68
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:79
#: .././gecosws_config_assistant/util/PackageManager.py:131
msgid "Package installation failed:"
msgstr ""

#: .././gecosws_config_assistant/dao/NTPServerDAO.py:95
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:523
#: .././gecosws_config_assistant/dao/WorkstationDataDAO.py:81
msgid "Error reading file:"
msgstr ""

#: .././gecosws_config_assistant/dao/NTPServerDAO.py:99
#: .././gecosws_config_assistant/dao/NTPServerDAO.py:135
msgid "NTPServerDAO used without a proper initialization!"
msgstr ""

#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:175
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:201
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:249
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:360
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:387
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:413
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:448
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:484
msgid "Error running command: "
msgstr ""

#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:498
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:540
#: .././gecosws_config_assistant/dao/UserAuthenticationMethodDAO.py:566
msgid "UserAuthenticationMethodDAO used without a proper initialization!"
msgstr ""

#: .././gecosws_config_assistant/dao/WorkstationDataDAO.py:133
msgid "Error writing file:"
msgstr ""

#: .././gecosws_config_assistant/util/JSONUtil.py:55
msgid "Error reading file: "
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:59
#: .././gecosws_config_assistant/util/PackageManager.py:99
#: .././gecosws_config_assistant/util/PackageManager.py:137
#: .././gecosws_config_assistant/util/PackageManager.py:161
#: .././gecosws_config_assistant/util/PackageManager.py:192
#: .././gecosws_config_assistant/util/PackageManager.py:231
msgid "No apt library available"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:79
#: .././gecosws_config_assistant/util/PackageManager.py:120
#: .././gecosws_config_assistant/util/PackageManager.py:183
#: .././gecosws_config_assistant/util/PackageManager.py:214
msgid "Package not found:"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:81
msgid "Package not installed:"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:83
msgid "Package not upgradable:"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:93
msgid "Package upgrade failed:"
msgstr ""

#. TODO: Yum version?
#: .././gecosws_config_assistant/util/PackageManager.py:104
msgid "Package upgrade failed!"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:122
msgid "Package already installed:"
msgstr ""

#. TODO: Yum version?
#: .././gecosws_config_assistant/util/PackageManager.py:142
msgid "Package installation failed!"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:155
msgid "Package update failed!"
msgstr ""

#. TODO: Yum version?
#: .././gecosws_config_assistant/util/PackageManager.py:166
msgid "Package cache update failed!"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:185
#: .././gecosws_config_assistant/util/PackageManager.py:216
msgid "Package is not installed:"
msgstr ""

#: .././gecosws_config_assistant/util/PackageManager.py:225
msgid "Package removal failed:"
msgstr ""

#. TODO: Yum version?
#: .././gecosws_config_assistant/util/PackageManager.py:236
msgid "Package removal failed!"
msgstr ""

#: .././gecosws_config_assistant/util/Template.py:150
msgid "Error saving template:"
msgstr ""

#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:66
msgid "Active Directory credentials needed"
msgstr ""

#. Explanation
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:79
msgid "To setup or remove the Active Directory authentication method you"
msgstr ""

#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:82
msgid "have to specify an AD administrator user and password:"
msgstr ""

#. Domain
#. text
#. Domain
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:87
#: .././gecosws_config_assistant/view/SystemStatusElemView.py:137
#: .././gecosws_config_assistant/view/UserAuthDialog.py:244
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:140
msgid "Domain:"
msgstr ""

#. Workgroup
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:94
#: .././gecosws_config_assistant/view/SystemStatusElemView.py:138
#: .././gecosws_config_assistant/view/UserAuthDialog.py:245
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:147
msgid "Workgroup:"
msgstr ""

#. User
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:101
#: .././gecosws_config_assistant/view/UserAuthDialog.py:246
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:154
msgid "User:"
msgstr ""

#. Password
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:111
#: .././gecosws_config_assistant/view/LocalUserElemView.py:98
#: .././gecosws_config_assistant/view/UserAuthDialog.py:247
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:163
msgid "Password:"
msgstr ""

#. Cancel button
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:122
#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:91
#: .././gecosws_config_assistant/view/LocalUserElemView.py:116
msgid "Cancel"
msgstr ""

#. Accept button
#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:127
#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:96
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:109
#: .././gecosws_config_assistant/view/LocalUserElemView.py:121
#: .././gecosws_config_assistant/view/LocalUserListView.py:128
#: .././gecosws_config_assistant/view/SystemStatusElemView.py:83
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:114
msgid "Accept"
msgstr ""

#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:164
msgid "Active Directory connection error"
msgstr ""

#: .././gecosws_config_assistant/view/ADSetupDataElemView.py:165
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""

#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:66
msgid "Url Chef Certificate Required"
msgstr ""

#. Explanation
#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:79
msgid ""
"You need to enter url with certificate file\n"
" in protocol://domain/resource format"
msgstr ""

#. Certificate URL
#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:83
msgid "Certificate URL:"
msgstr ""

#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:121
msgid "URL connection error"
msgstr ""

#: .././gecosws_config_assistant/view/ChefValidationCertificateDialog.py:122
msgid "Can't get certificate file from this URL"
msgstr ""

#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:51
msgid "GECOS CC connection process"
msgstr ""

#. Checking GECOS credentials
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:64
msgid "Check GECOS credentials"
msgstr ""

#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:67
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:74
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:81
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:88
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:95
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:102
msgid "PENDING"
msgstr ""

#. Checking workstation data
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:71
msgid "Check workstation data"
msgstr ""

#. Obtaining Chef validation certificate
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:78
msgid "Get chef certificate"
msgstr ""

#. Registering computer in GECOS CC
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:92
msgid "Register in GECOS"
msgstr ""

#. Removing old configuration files
#: .././gecosws_config_assistant/view/GecosCCSetupProcessView.py:99
msgid "Clean setup data"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserElemView.py:65
#: .././gecosws_config_assistant/view/LocalUserElemView.py:141
msgid "Add local user"
msgstr ""

#. Name
#: .././gecosws_config_assistant/view/LocalUserElemView.py:79
msgid "Name:"
msgstr ""

#. Login
#: .././gecosws_config_assistant/view/LocalUserElemView.py:88
#: .././gecosws_config_assistant/view/SystemStatusElemView.py:121
msgid "Login:"
msgstr ""

#. Password confirmation
#: .././gecosws_config_assistant/view/LocalUserElemView.py:107
msgid "Confirm:"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserElemView.py:133
msgid "Modifiy local user"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserElemView.py:155
msgid "The password confirmation field is empty!"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserElemView.py:163
msgid "The password confirmation is different from password"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserListView.py:62
msgid "Manage local users"
msgstr ""

#. Explanation
#: .././gecosws_config_assistant/view/LocalUserListView.py:75
msgid "You can create, update or delete local users in this workstation."
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserListView.py:78
msgid ""
"It isn't necessary to create here the users that are authenticated by "
"external services (LDAP, AD, ...)"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserListView.py:84
msgid "Please check default OEM users and change their passwords when needed:"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserListView.py:92
msgid "Login"
msgstr ""

#: .././gecosws_config_assistant/view/LocalUserListView.py:93
msgid "Name"
msgstr ""

#. New user button
#: .././gecosws_config_assistant/view/LocalUserListView.py:112
msgid "New"
msgstr ""

#. Update user button
#: .././gecosws_config_assistant/view/LocalUserListView.py:117
msgid "Update"
msgstr ""

#. Delete user button
#: .././gecosws_config_assistant/view/LocalUserListView.py:122
msgid "Delete"
msgstr ""

#: .././gecosws_config_assistant/view/NTPServerElemView.py:109
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""

#: .././gecosws_config_assistant/view/NTPServerElemView.py:112
msgid "NTP server connection successful"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:65
msgid "System status"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:96
#: .././gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "Assistant version: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:98
msgid "UNKNOWN VERSION"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:103
msgid "Workstation name: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:108
msgid "Time server: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:111
msgid "Network interfaces: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:117
msgid "GECOS Control Center connection data: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:120
msgid "Server URL:"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:124
msgid "Local users: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:131
msgid "User authentication method: "
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:134
msgid "Method:"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:141
msgid "Server URI:"
msgstr ""

#. Users base DN
#: .././gecosws_config_assistant/view/SystemStatusElemView.py:142
#: .././gecosws_config_assistant/view/UserAuthDialog.py:213
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:219
msgid "Users base DN:"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:143
msgid "Groups base DN:"
msgstr ""

#: .././gecosws_config_assistant/view/SystemStatusElemView.py:148
msgid "No status data!"
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthDialog.py:209
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:207
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""

#. text
#. URI
#: .././gecosws_config_assistant/view/UserAuthDialog.py:212
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:212
msgid "LDAP server URI:"
msgstr ""

#. Groups base DN
#: .././gecosws_config_assistant/view/UserAuthDialog.py:214
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:226
msgid "Groups base DN (optional):"
msgstr ""

#. Bind user DN
#: .././gecosws_config_assistant/view/UserAuthDialog.py:215
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:233
msgid "Bind user DN (optional):"
msgstr ""

#. Bind user password
#: .././gecosws_config_assistant/view/UserAuthDialog.py:216
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:241
msgid "Bind user password (optional):"
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthDialog.py:241
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:136
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthDialog.py:272
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:287
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthDialog.py:364
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:378
msgid "An error happened while saving the users authentication method!"
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:72
msgid "User authentication method"
msgstr ""

#. Explanation
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:85
msgid "The users of this workstation may authenticate by using"
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:88
msgid "an external system like LDAP or Microsoft Active Directory."
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:91
msgid "Also, they can be authenticated by using local users of this O.S."
msgstr ""

#. Authentication Type
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:95
msgid "Authentication type:"
msgstr ""

#. Setup button
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:109
msgid "Setup"
msgstr ""

#. Options frame
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:125
msgid "Active Directory authentication"
msgstr ""

#. Options frame
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:196
msgid "LDAP authentication"
msgstr ""

#. Options frame
#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:276
msgid "Local users authentication"
msgstr ""

#: .././gecosws_config_assistant/view/UserAuthenticationMethodElemView.py:377
msgid "Error saving authentication method"
msgstr ""
